#!/usr/bin/env bash
# Move criterion's saved baseline estimates between a criterion tree and a
# standalone cache directory.
#
#   ab-baseline.sh stage <criterion-dir> <baseline-dir>   criterion -> cache
#   ab-baseline.sh load  <baseline-dir> <criterion-dir>   cache -> criterion
#
# The baseline is cached OUTSIDE target/ on purpose. It used to live at
# target/criterion/*/*/main, which meant a build cache over target/ and the
# exact-SHA baseline cache were writing to the same tree - and a stale restore
# there would silently compare a PR against the wrong baseline, the one failure
# the baseline cache's missing restore-keys exists to prevent.
#
# Only the `main/` directories are moved: those are criterion's saved-baseline
# estimates. new/, change/ and report/ are regenerated by the comparison run.
set -euo pipefail

mode="${1:-}"
src="${2:-}"
dest="${3:-}"

if [[ -z "$mode" || -z "$src" || -z "$dest" ]]; then
  echo "usage: ab-baseline.sh <stage|load> <src> <dest>" >&2
  exit 2
fi

case "$mode" in
  stage|load) ;;
  *) echo "error: unknown mode '$mode' (expected stage or load)" >&2; exit 2 ;;
esac

if [[ ! -d "$src" ]]; then
  # `load` with no cached baseline is a real error: the comparison run would
  # otherwise proceed with nothing to compare against and report every
  # benchmark as new rather than failing visibly.
  echo "error: $src does not exist; nothing to $mode" >&2
  exit 1
fi

copied=0
for d in "$src"/*/*/main; do
  [[ -d "$d" ]] || continue
  rel="${d#"$src"/}"
  mkdir -p "$dest/${rel%/main}"
  # Remove any existing main/ first. `cp -r src dest` copies INTO dest when dest
  # is an existing directory, so without this a criterion tree already present
  # (restored by the build cache) would keep its stale estimates.json at
  # main/estimates.json and bury the real baseline at main/main/estimates.json -
  # and the comparison reads the former, silently scoring the PR against the
  # wrong commit.
  rm -rf "$dest/${rel}"
  cp -r "$d" "$dest/${rel}"
  copied=$((copied + 1))
done

if [[ "$copied" -eq 0 ]]; then
  echo "error: no baseline estimates found under $src/*/*/main" >&2
  exit 1
fi

echo "$mode: copied $copied baseline estimate directories from $src to $dest"
